"""new change runway_workflow

Revision ID: 23e4f386d8bc
Revises: 28c817cfe691
Create Date: 2026-03-26 04:41:53.448421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23e4f386d8bc'
down_revision: Union[str, None] = '28c817cfe691'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('published_posts', sa.Column('generated_asset_id', sa.Integer(), nullable=False))
    op.add_column('published_posts', sa.Column('workflow', sa.String(length=100), nullable=False))
    op.add_column('published_posts', sa.Column('provider', sa.String(length=100), nullable=False))
    op.drop_index('ix_published_posts_content_idea_id', table_name='published_posts')
    op.create_index(op.f('ix_published_posts_content_idea_id'), 'published_posts', ['content_idea_id'], unique=False)
    op.create_index(op.f('ix_published_posts_generated_asset_id'), 'published_posts', ['generated_asset_id'], unique=False)
    op.create_foreign_key(None, 'published_posts', 'generated_assets', ['generated_asset_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'published_posts', type_='foreignkey')
    op.drop_index(op.f('ix_published_posts_generated_asset_id'), table_name='published_posts')
    op.drop_index(op.f('ix_published_posts_content_idea_id'), table_name='published_posts')
    op.create_index('ix_published_posts_content_idea_id', 'published_posts', ['content_idea_id'], unique=True)
    op.drop_column('published_posts', 'provider')
    op.drop_column('published_posts', 'workflow')
    op.drop_column('published_posts', 'generated_asset_id')
    # ### end Alembic commands ###
