"""add app events table

Revision ID: 28c817cfe691
Revises: a7887c7c88a6
Create Date: 2026-03-24 18:34:53.287605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28c817cfe691'
down_revision: Union[str, None] = 'a7887c7c88a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('event_name', sa.String(length=255), nullable=False),
    sa.Column('feature_name', sa.String(length=255), nullable=True),
    sa.Column('event_value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_events_created_at'), 'app_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_app_events_event_name'), 'app_events', ['event_name'], unique=False)
    op.create_index(op.f('ix_app_events_feature_name'), 'app_events', ['feature_name'], unique=False)
    op.create_index(op.f('ix_app_events_id'), 'app_events', ['id'], unique=False)
    op.create_index(op.f('ix_app_events_user_id'), 'app_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_events_user_id'), table_name='app_events')
    op.drop_index(op.f('ix_app_events_id'), table_name='app_events')
    op.drop_index(op.f('ix_app_events_feature_name'), table_name='app_events')
    op.drop_index(op.f('ix_app_events_event_name'), table_name='app_events')
    op.drop_index(op.f('ix_app_events_created_at'), table_name='app_events')
    op.drop_table('app_events')
    # ### end Alembic commands ###
