"""add scripts and video prompts tables

Revision ID: 54463f7e7d63
Revises: dabaf4c871ab
Create Date: 2026-03-17 05:28:29.836324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54463f7e7d63'
down_revision: Union[str, None] = 'dabaf4c871ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_idea_id', sa.Integer(), nullable=False),
    sa.Column('hook', sa.Text(), nullable=False),
    sa.Column('script_text', sa.Text(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=False),
    sa.Column('hashtags', sa.Text(), nullable=False),
    sa.Column('voiceover_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_idea_id'], ['content_ideas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scripts_content_idea_id'), 'scripts', ['content_idea_id'], unique=True)
    op.create_index(op.f('ix_scripts_id'), 'scripts', ['id'], unique=False)
    op.create_table('video_prompts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_idea_id', sa.Integer(), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('shot_list', sa.Text(), nullable=False),
    sa.Column('visual_style', sa.Text(), nullable=False),
    sa.Column('camera_notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_idea_id'], ['content_ideas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_prompts_content_idea_id'), 'video_prompts', ['content_idea_id'], unique=True)
    op.create_index(op.f('ix_video_prompts_id'), 'video_prompts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_prompts_id'), table_name='video_prompts')
    op.drop_index(op.f('ix_video_prompts_content_idea_id'), table_name='video_prompts')
    op.drop_table('video_prompts')
    op.drop_index(op.f('ix_scripts_id'), table_name='scripts')
    op.drop_index(op.f('ix_scripts_content_idea_id'), table_name='scripts')
    op.drop_table('scripts')
    # ### end Alembic commands ###
