"""add published posts table

Revision ID: a7887c7c88a6
Revises: 3b60af31fb52
Create Date: 2026-03-18 18:02:49.815638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7887c7c88a6'
down_revision: Union[str, None] = '3b60af31fb52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('published_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_idea_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('platform_post_id', sa.String(length=255), nullable=False),
    sa.Column('publish_status', sa.String(length=50), nullable=False),
    sa.Column('caption_used', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_idea_id'], ['content_ideas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_published_posts_content_idea_id'), 'published_posts', ['content_idea_id'], unique=True)
    op.create_index(op.f('ix_published_posts_id'), 'published_posts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_published_posts_id'), table_name='published_posts')
    op.drop_index(op.f('ix_published_posts_content_idea_id'), table_name='published_posts')
    op.drop_table('published_posts')
    # ### end Alembic commands ###
